name: pre-merge-e2e-tests

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install --ignore-optional # will run `yarn install` command
      - run: npm run test