name: Publish sdk-dapp

on:
  push:
    branches: [main]
  repository_dispatch:
    types: publish-npm
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: kevin-bronsdijk/npm-pre-release-packages-detection-action@v1.0.0
        id: npmprerelease
        with:
          package-file-full-path: './package.json'
      - run: echo "result ${{ steps.npmprerelease.outputs.found-pre-release }}"
