name: Publish sdk-dapp

on:
  push:
    branches: [main]
  repository_dispatch:
    types: publish-npm
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Get package info
        id: package
        uses: andreigiura/action-nodejs-package-info@v1.0.2

      - name: Publish to npmjs next version
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.package.outputs.is-prerelease}}
        run: echo ${{ steps.package.outputs.is-prerelease}} && cd dist && npm publish --dry-run --tag next

      - name: Publish to npmjs
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ !steps.package.outputs.is-prerelease}}
        run: cd dist && npm publish --dry-run
