name: Publish sdk-dapp

on:
  push:
    branches: [main]
  repository_dispatch:
    types: publish-npm
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Get package info
        id: package
        uses: codex-team/action-nodejs-package-info@v1.1
      - run: echo "is-release-candidate: ${{ steps.package.outputs.is-release-candidate }}"
