name: Pre release dapp-core

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  prerelease-npm:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: 'develop'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: 'feature, automated pr'
          pr_title: '[Example] Simple demo'
